---
kind: pipeline
type: docker
name: verify-pr
steps:
- name: build-dry-run
  image: plugins/docker
  settings:
    repo: lblod/frontend-embeddable-editor
    dry_run: true
    purge: true
- name: test
  image: danlynn/ember-cli:3.20.0
  commands:
  - npm install
  - npm test
trigger:
  event:
    - pull_request

---
kind: pipeline
type: docker
name: push-latest-build
steps:
- name: push-latest-build
  image: plugins/docker
  settings:
    repo: lblod/frontend-embeddable-editor
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    purge: true
trigger:
  branch:
    - development
  event:
    exclude:
    - pull_request
---
kind: pipeline
type: docker
name: release
steps:
- name: push-tagged-build
  image: plugins/docker
  settings:
    repo: lblod/frontend-embeddable-editor
    tags: ${DRONE_TAG##v}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    purge: true
trigger:
  event:
    - tag
---
kind: secret
name: docker_username
data: HXC8pZ1VXDfM56k+lF5rWHF2vQ44lCiUNmbC5kTHt9EQahQGSOlqig==
---
kind: secret
name: docker_password
data: M75cyHu+IxPrb5LePaeHUpf4Nq5YBgxmSLB+uQFwbiuqeHUrUae5q3e5tuQEt9MA/me6bqqJMMHhTQ13gEaTfA==
---
kind: signature
hmac: ae4aed20849b5724a8e4604c115092dc9eb6ffd1e0e659601697be5fbda91ef8

...
