steps:
  cypress:
    image: cypress/included:cypress-13.6.1-node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1
    commands:
      - npm ci
      - npm run ci
    failure: ignore
when:
  event:
    - pull_request
