pipeline:
  push-latest:
    image: plugins/docker
    settings:
      repo: lblod/frontend-embeddable-editor
      tags: latest
    secrets: [ docker_username, docker_password ]
when:
  branch: master
  event: push
