steps:
  install:
    image: danlynn/ember-cli:4.12.1
    commands:
      - npm ci --ignore-scripts
  publish:
    image: plugins/npm
    settings:
      token:
        from_secret: npm_access_token
      access: public
  push-tagged-build:
    image: plugins/docker
    settings:
      repo: lblod/embeddable-say-editor-test
      tags: "${CI_COMMIT_TAG##v}"
      purge: true
    secrets: [ docker_username, docker_password ]
when:
  event: tag
  ref: refs/tags/v*
