steps:
  install:
    image: danlynn/ember-cli:4.12.1
    commands:
      - npm ci --ignore-scripts
  publish-pre-release:
    image: plugins/npm
    settings:
      token:
        from_secret: npm_access_token
      access: public
      tag: next
    when:
      ref:
        include: refs/tags/*-next.*
  publish:
    image: plugins/npm
    settings:
      token:
        from_secret: npm_access_token
      access: public
    when:
      ref:
        exclude: refs/tags/*-next.*
  push-tagged-build:
    image: plugins/docker
    settings:
      dockerfile: test-app/Dockerfile
      repo: lblod/embeddable-say-editor-test
      tags: "${CI_COMMIT_TAG##v}"
      purge: true
    secrets: [ docker_username, docker_password ]
when:
  event: tag
  ref: refs/tags/v*
