steps:
  publish-pre-release:
    image: node:20-slim
    commands:
      - export NPM_TOKEN=$NPM_ACCESS_TOKEN
      - npm i -g corepack@0.31
      - pnpm i --frozen-lockfile --ignore-scripts
      - pnpm publish embeddable-say-editor --tag next --no-git-checks --access public
    secrets: [npm_access_token]
    when:
      ref:
        include: refs/tags/@lblod/*-next.*
  publish:
    image: node:20-slim
    commands:
      - export NPM_TOKEN=$NPM_ACCESS_TOKEN
      - npm i -g corepack@0.31
      - pnpm i --frozen-lockfile --ignore-scripts
      - pnpm publish embeddable-say-editor --tag latest --no-git-checks --access public
    secrets: [npm_access_token]
    when:
      ref:
        exclude: refs/tags/@lblod/*-next.*
  push-tagged-build:
    image: plugins/docker
    settings:
      repo: lblod/frontend-embeddable-notule-editor
      dockerfile: test-app/Dockerfile
      tags: ${CI_COMMIT_TAG##\@lblod/embeddable-say-editor\@}
      purge: true
    secrets: [docker_username, docker_password]
when:
  event: tag
  ref: refs/tags/@lblod/embeddable-say-editor@*
