pipeline:
  install:
    image: danlynn/ember-cli:4.8.0
    commands:
      - npm ci
  release:
    image: plugins/npm
    settings:
      token:
        from_secret: npm_access_token
  push-tagged-build:
    image: plugins/docker
    settings:
      repo: lblod/frontend-embeddable-editor
      tags: "${CI_COMMIT_TAG##v}"
      secrets: [ docker_username, docker_password ]
      purge: true
when:
  event: tag
  tag: v*
