steps:
  install:
    image: node:20-slim
    commands:
      - corepack enable
      - pnpm i --frozen-lockfile --ignore-scripts
  publish-pre-release:
    image: codeberg.org/woodpecker-plugins/node-pm
    settings:
      run: publish embeddable-say-editor --otp $NPM_ACCESS_TOKEN --tag next --no-git-checks --access public
      frozen_lockfile: true
      ignore_node_modules: true
      secrets: [npm_access_token]
    when:
      ref:
        include: refs/tags/**-next.*
  publish:
    image: plugins/npm
    settings:
      token:
        from_secret: npm_access_token
      access: public
      folder: embeddable-say-editor
    when:
      ref:
        exclude: refs/tags/**-next.*
  push-tagged-build:
    image: plugins/docker
    settings:
      repo: lblod/frontend-embeddable-notule-editor
      dockerfile: test-app/Dockerfile
      tags: ${CI_COMMIT_TAG##\@lblod/embeddable-say-editor\@}
      purge: true
    secrets: [ docker_username, docker_password ]
when:
  event: tag
  ref: refs/tags/@lblod/embeddable-say-editor@*
