steps:
  install:
    image: danlynn/ember-cli:4.12.1
    commands:
      - npm ci --ignore-scripts
  publish-pre-release:
    image: plugins/npm
    settings:
      token:
        from_secret: npm_access_token
      access: public
      folder: embeddable-say-editor
      tag: next
    when:
      ref:
        include: refs/tags/*-next.*
  publish:
    image: plugins/npm
    settings:
      token:
        from_secret: npm_access_token
      access: public
      folder: embeddable-say-editor
    when:
      ref:
        exclude: refs/tags/*-next.*
when:
  event: tag
  ref: refs/tags/v*
