steps:
  install:
    image: danlynn/ember-cli:3.28.5
    commands:
      - npm ci
  lint-js:
    image: danlynn/ember-cli:3.28.5
    group: lint
    commands:
      - npm run lint:js
  lint-hbs:
    image: danlynn/ember-cli:3.28.5
    group: lint
    commands:
      - npm run lint:hbs
  test:
    image: danlynn/ember-cli:3.28.5
    commands:
      - npm run test:ember
when:
  event:
    - pull_request