steps:
  install:
    image: node:20-slim
    commands:
      - corepack enable
      - pnpm i --frozen-lockfile
  lint-js:
    image: node:20-slim
    group: lint
    commands:
      - corepack enable
      - pnpm lint:js
  lint-hbs:
    image: node:20-slim
    group: lint
    commands:
      - corepack enable
      - pnpm lint:hbs
  dependency-lint:
    image: node:20-slim
    group: lint
    commands:
      - corepack enable
      - pnpm lint:dependencies
when:
  event:
    - pull_request
