steps:
  install:
    image: node:20-slim
    commands:
      - corepack enable
      - pnpm i --frozen-lockfile
  lint-js:
    image: node:20-slim
    group: lint
    commands:
      - corepack enable
      - pnpm lint:js
  lint-hbs:
    image: node:20-slim
    group: lint
    commands:
      - corepack enable
      - pnpm lint:hbs
  dependency-lint:
    image: node:20-slim
    group: lint
    commands:
      - corepack enable
      - pnpm lint:dependencies
  test-angular:
    image: plugins/docker
    settings:
      repo: lblod/frontend-embeddable-notule-editor
      dockerfile: test-angular/Dockerfile
      dry_run: true
when:
  event:
    - pull_request
